#!/bin/bash



for file in "$1"/*; do
	prefix=$(echo "$file" | gsed -E "s/^(.*)-([0-9]?)/\2/g")
	filename=$(echo "$file" | gsed -E "s/^$1(.*)\//\1/g")
	
#	echo $prefix
#	echo $filename
	if ! [[ ${prefix: -3} = ${filename: -3} ]]; then 
		mv $file "$1/$prefix.$filename"

	fi

done
